name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - master
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: setup node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: install pnpm
      run: npm i pnpm@latest -g
    - name: install dependencies
      run: pnpm install --frozen-lockfile=false
    - name: test
      run: pnpm test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        milliseconds: 1000
